// Code generated by goctl. DO NOT EDIT.
package types

type VideoListRequest struct {
}

type VideoListReply struct {
	StatusCode int64       `json:"status_code"` // 状态码，0-成功，其他值-失败
	StatusMsg  string      `json:"status_msg"`  // 返回状态描述
	VideoList  interface{} `json:"video_list"`  // 用户发布的视频列表
}

type VideoUploadRequest struct {
	Title    string `form:"title"`
	Path     string `json:"path,optional"`
	Hash     string `json:"hash,optional"`
	UserId   int64  `json:"userId,optional"`
	UserName string `json:"userName,optional"`
}

type VideoUploadReply struct {
	StatusCode int64  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type UserDetailRequest struct {
	User_id string `json:"userId"`
	Token   string `json:"token"`
}

type UserDetailReply struct {
	StatusCode int64       `json:"status_code"` // 状态码，0-成功，其他值-失败
	StatusMsg  string      `json:"status_msg"`  // 返回状态描述
	User       interface{} `json:"user"`
}

type FeedRequest struct {
}

type FeedResponse struct {
	NextTime   *int64      `json:"next_time"`   // 本次返回的视频中，发布最早的时间，作为下次请求时的latest_time
	StatusCode int64       `json:"status_code"` // 状态码，0-成功，其他值-失败
	StatusMsg  string      `json:"status_msg"`  // 返回状态描述
	VideoList  interface{} `json:"video_list"`  // 视频列表
}

type UserRegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserRegisterReply struct {
	StatusCode int64  `json:"status_code"` // 状态码，0-成功，其他值-失败
	StatusMsg  string `json:"status_msg"`  // 返回状态描述
	Token      string `json:"token"`       // 用户鉴权token
	UserID     int64  `json:"user_id"`     // 用户id
}

type UserLoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserLoginReply struct {
	StatusCode int64  `json:"status_code"` // 状态码，0-成功，其他值-失败
	StatusMsg  string `json:"status_msg"`  // 返回状态描述
	Token      string `json:"token"`       // 用户鉴权token
	UserID     int64  `json:"user_id"`     // 用户id
}
